[package]
name = "ocean"
version = "0.1.0"
description = "Ocean - Desktop workspace organizer"
authors = ["Ocean Team"]
license = ""
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.7", features = [ "window-close", "window-hide", "window-show", "window-set-title", "window-set-size", "window-set-position", "window-center", "window-create", "http-request", "fs-read-dir", "fs-copy-file", "fs-exists", "fs-write-file", "fs-create-dir", "fs-remove-file", "dialog-save", "fs-read-file", "fs-remove-dir", "dialog-open", "fs-rename-file", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
